version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -p 3000 -b '0.0.0.0'"
#    command: tail -f /var/log/dpkg.log
    volumes:
      - .:/jalecitos
    environment:
      - RAILS_ENV=development
      - SECRET_KEY_BASE=dumapaikqwdkqmwuqcb287deuivk3837nmvk92wn1kwnkelleo
      - REDIS_URL=redis://redis:6379/1
      - DEVISE_SECRET_KEY=qowndkqwdkqmwuqcb287dbwe9220192wn1kwnso1i
      - GOOGLE_MAP_API=AIzaSyCISaREiwuF3yhIceGw2Rohlj9OnoRJukk
      - FACEBOOK_ID=307778330022720
      - FACEBOOK_SECRET=0486dbcf6b932519e4f14c10e421c4c3
      - FACEBOOK_CALLBACK=http://local.jalecitos.com/users/auth/facebook/callback
      - EMAIL_API_TOKEN=a1uK0wsA1ClL9SCynPmj2g
      - S3_BUCKET_NAME=local.jalecitos.com
      - AWS_ACCESS_KEY_ID=AKIAI7WWMNOBVY4IKSBQ
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_REGION=us-east-2
      # Open API
      - OPENPAY_PROD=false
      - OPENPAY_MERCHANT_ID=mgaglakzbv6gzvpnzp6g
      - OPENPAY_PRIVATE_KEY=sk_4c6a3e0b2c9c406b91fd6fbe5eddaeeb
      - OPENPAY_PUBLIC_KEY=pk_c958326b8eb44e8b8ace1001948cb0ab
      - ELASTICSEARCH_URL=http://elasticsearch:9200


    ports:
      - "80:3000"
    depends_on:
      - db

  adminer:
    image: adminer
    ports:
      - 8080:8080

  redis:
    image: redis
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:6.4.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
