version: '3'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        US_ID: $US_ID
        GR_ID: $GR_ID
    image: jalecitos-rails_app:latest
    command: web
    volumes:
      - .:/home/wand/app
    env_file:
      - .env
    depends_on:
      - db

  sidekiq:
    image: jalecitos-rails_app:latest
    command: sidekiq
    depends_on:
      - redis
      - db
      - app
    volumes:
      - .:/home/wand/app
    env_file:
      - .env

  adminer:
    image: adminer

  redis:
    image: redis

  elasticsearch:
    image: elasticsearch:6.4.2
    environment:
      - discovery.type=single-node

volumes:
  postgres-volume:
  elasticsearch-volume:
