#!/bin/bash

function start() {
  set -e
  read -p "Delete DB folder to start from scratch? (y/n): " DBDEL
  read -p "Create DB and migrations on startup? (y/n): " DBCREATE
  if [ "$DBDEL" == "y" ]
  then
    echo "Deleting DB folder..."
    sudo rm -rf tmp/db/
    echo "done."
  fi
  docker-compose up -d --build --force-recreate
  if [ "$DBCREATE" == "y" ]
  then
    bash $0 create-db
  fi
}

function stop() {
  docker-compose down
}

function create_db() {
  docker-compose exec app rails db:create
  docker-compose exec app rails db:migrate
}

function generate_db_diagram {
  bash $0 run rake diagram:all
}

function path {
  export PATH=$PATH:$(pwd)
}

case $1 in
  start)
    start
  ;;
  stop)
    stop
  ;;
  create-db)
    create_db
  ;;
  run)
    shift
    docker-compose exec app $@
  ;;
  restart)
    stop
    start
  ;;
  fix-perms)
    sudo chown -R $USER:$USER app/
  ;;
  db_diag)
    generate_db_diagram
  ;;
  path)
    path
  ;;
  *)
    echo "
    Usage:
    $0 path                Export cli to your shell
    $0 start/stop          Start the project by using docker-compose
    $0 create-db           Run db create and migrations
    $0 run command here    Run any command inside the container
    $0 fix-perms           Experimental - fix code permission issues
    $0 db_diag             Export DB diagram"
  ;;
esac
