development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_ACTIONCABLE") { "redis://redis:6379/1" } %>

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL_ACTIONCABLE") { "redis://redis:6379/1" } %>
