default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  host: <%= ENV.fetch("DB_HOST") { "db" } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") {}%>
  variables:
    statement_timeout: 5000

development:
  <<: *default
  database: jalecitos_development


test:
  <<: *default
  database: jalecitos_test%

staging:
  <<: *default
  database: staging


production:
  <<: *default
  database: jalecitos
