generate_sitemap_job:
  # cron: "*/1 * * * *"
  cron: "0 1 * * *"
  class: "RegenerateSitemapWorker"
pending_refunds_job:
  # cron: "*/1 * * * *"
  cron: "0 2 * * *"
  class: "PendingRefundsWorker"
run_marketing_notifications:
  cron: "*/30 * * * *"
  class: "RunMarketingNotificationsWorker"
deny_waiting_orders:
  cron: "0 2 * * *"
  class: "DenyWaitingOrdersWorker"
close_requests_job:
  # cron: "*/1 * * * *"
  cron: "0 3 * * *"
  class: "CloseRequestWorker"  
